import streamlit as st
import sqlite3
import pandas as pd
import numpy as np
import pickle
import os
import plotly.express as px

DB_PATH = os.path.join("data", "campaign_data.db")
OUTPUT_DIR = "output"

st.set_page_config(page_title="Political Strategy & Micro-Targeting Engine", layout="wide")

# 1. Title and Header
st.title("🎯 Political Micro-Targeting & Strategy Engine")
st.markdown("---")

# Load data from the SQL table generated by modeling.py
@st.cache_data
def load_dashboard_data():
    conn = sqlite3.connect(DB_PATH)
    df = pd.read_sql_query("SELECT * FROM model_output", conn)
    conn.close()
    return df

df = load_dashboard_data()

# 2. Key Metrics Row
total_voters = int(df['total_registered_voters'].sum())
avg_turnout = df['turnout_pct'].mean()
avg_dem_share = df['dem_share_pct'].mean()

m1, m2, m3 = st.columns(3)
m1.metric("Total District Voters", f"{total_voters:,}")
m2.metric("Average Turnout Rate", f"{avg_turnout:.1f}%")
m3.metric("Average Party Share", f"{avg_dem_share:.1f}%")

st.markdown("---")

# 3. Sidebar Filter Option
st.sidebar.header("Campaign Control Panel")
selected_cluster = st.sidebar.selectbox(
    "Select Target Voter Cluster Persona:",
    options=sorted(df['voter_cluster'].unique()),
    format_func=lambda x: f"Cluster {x}: " + (
        "Progressive Renters (Lean Dem)" if x == 0 else
        "Conservative Seniors (Lean Rep)" if x == 1 else
        "Working-Class Moderates (Swing)" if x == 2 else "Affluent Suburbanites"
    )
)

# Filter dataframe based on selected cluster
cluster_df = df[df['voter_cluster'] == selected_cluster]

# 4. Analytics and Visualizations
col1, col2 = st.columns(2)

with col1:
    st.subheader(f"📊 Demographics for Target Cluster {selected_cluster}")
    # Show scatter plot comparing income vs age for the cluster
    fig = px.scatter(
        df, x="median_income", y="median_age", color="voter_cluster",
        title="District-Wide Cluster Segmentation Map",
        labels={"median_income": "Median Income ($)", "median_age": "Median Age"},
        color_continuous_scale=px.colors.sequential.Viridis
    )
    st.plotly_chart(fig, use_container_width=True)

with col2:
    st.subheader("💡 Strategic Consulting Campaign Recommendations")
    
    # Custom campaign playbook strategies based on cluster attributes
    if selected_cluster == 0:
        st.error("🚨 **Target Persona:** Young Progressive Renters")
        st.write("• **Message Strategy:** Focus heavily on housing affordability, student debt relief, and environmental policies.")
        st.write("• **Media Mix:** Allocate 70% of budget to TikTok, Instagram reels, and targeted digital ads.")
        st.write("• **Field Action:** Deploy volunteers for massive door-to-door canvas sweeps near local universities.")
    elif selected_cluster == 1:
        st.info("🔵 **Target Persona:** High-Income Conservative Seniors")
        st.write("• **Message Strategy:** Emphasize tax reductions, government accountability, and localized economic growth.")
        st.write("• **Media Mix:** Leverage traditional local news, direct mailers, and highly tailored Facebook groups.")
        st.write("• **Field Action:** Organize neighborhood townhalls and coordinate senior-focused absentee ballot drives.")
    elif selected_cluster == 2:
        st.warning("⚡ **Target Persona:** Working-Class Moderates (CRITICAL SWING VOTERS)")
        st.write("• **Message Strategy:** Stick strictly to bread-and-butter economic issues, local inflation offsets, and local job creation.")
        st.write("• **Media Mix:** Invest heavily in local radio, YouTube pre-roll ads, and localized community newsletters.")
        st.write("• **Field Action:** Focus phone banks and door knocks specifically on high-priority independent voters.")
    else:
        st.success("🟢 **Target Persona:** Affluent Suburbanites")
        st.write("• **Message Strategy:** Focus on public infrastructure development, healthcare accessibility, and school systems.")
        st.write("• **Media Mix:** Digital news outlets, targeted LinkedIn distribution campaigns, and high-impact direct mail.")
        st.write("• **Field Action:** Set up professional volunteer networks to host localized backyard neighborhood events.")

st.markdown("---")

# 5. Machine Learning Turnout Prediction Tool
st.subheader("🔮 ML Precinct Turnout Predictive Simulator")
st.write("Simulate changes in a newly added or modified custom precinct to instantly predict voter turnout percentages via your live XGBoost engine.")

p1, p2, p3, p4 = st.columns(4)
sim_income = p1.slider("Median Income ($)", 30000, 140000, 65000)
sim_college = p2.slider("College Degree (%)", 10.0, 95.0, 45.0)
sim_age = p3.slider("Median Age", 22.0, 68.0, 41.0)
sim_renter = p4.slider("Renter Ratio (%)", 5.0, 85.0, 30.0)

# Load the trained model to calculate predictions on the fly
try:
    with open(os.path.join(OUTPUT_DIR, "turnout_xgboost.pkl"), "rb") as f:
        xgboost_model = pickle.load(f)
        
    input_data = pd.DataFrame([[sim_income, sim_college, sim_age, sim_renter]], 
                              columns=['median_income', 'college_degree_pct', 'median_age', 'renter_pct'])
    
    predicted_turnout = xgboost_model.predict(input_data)[0]
    st.info(f"🔮 **XGBoost Engine Predicted Turnout Rate for this Simulated Area:** `{predicted_turnout:.2f}%`")
except Exception as e:
    st.error("Could not load the turnout prediction model. Please ensure modeling.py ran completely.")
